CC = g++
PROGRAM_NAME = main

all: main.h main.cpp Utils.h Utils.cpp Distances.h Distances.cpp ClusteringAlgorithm.h ClusteringAlgorithm.cpp
	$(CC) Utils.cpp Distances.cpp ClusteringAlgorithm.cpp main.cpp -o $(PROGRAM_NAME)